on: [push]

name: test_nestbox

jobs:
  check:
    name: nestbox
    runs-on: ubuntu-latest
    steps:
      - name: Install latest stable
        uses: actions/checkout@v2
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Start mongod
        run: sudo systemctl start mongod
      - name: Run database_bouncycastle test
        run: cd database_bouncycastle && cargo test
        #- name: Restore mongo test db
        #run: mongorestore nestboxd/test_db_dump
        #- name: Run nestboxd test
        #run: cd nestboxd && cargo test
        
